version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      # rootユーザーのパスワード
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/var_lib_mysql:/var/lib/mysql
      # /docker-entrypoint-initdb.d/配下は、Dockerコンテナが初回起動（初期化）される際に１度だけ実行されるスクリプトなどを配置

      
